#include <DxLib.h>
#include "Color.h"
Color::Color() : rgb() {
	rgb[White].r           = 241; rgb[White].g           = 241; rgb[White].b           = 241;
	rgb[PearlGray].r       = 173; rgb[PearlGray].g       = 173; rgb[PearlGray].b       = 173;
	rgb[SilverGray].r      = 160; rgb[SilverGray].g      = 160; rgb[SilverGray].b      = 160;
	rgb[AshGrey].r         = 147; rgb[AshGrey].g         = 147; rgb[AshGrey].b         = 147;
	rgb[Grey].r            = 121; rgb[Grey].g            = 121; rgb[Grey].b            = 121;
	rgb[Black].r           =  28; rgb[Black].g           =  28; rgb[Black].b           =  28;
	rgb[Vermilion].r       = 237; rgb[Vermilion].g       =  81; rgb[Vermilion].b       =  78;
	rgb[Scarlet].r         = 222; rgb[Scarlet].g         =  67; rgb[Scarlet].b         =  53;
	rgb[Terracotta].r      = 172; rgb[Terracotta].g      =  86; rgb[Terracotta].b      =  71;
	rgb[SalmonPink].r      = 255; rgb[SalmonPink].g      = 165; rgb[SalmonPink].b      = 148;
	rgb[ShellPink].r       = 251; rgb[ShellPink].g       = 204; rgb[ShellPink].b       = 195;
	rgb[NailPink].r        = 241; rgb[NailPink].g        = 190; rgb[NailPink].b        = 177;
	rgb[Chocolate].r       =  82; rgb[Chocolate].g       =  55; rgb[Chocolate].b       =  47;
	rgb[BurntSienna].r     = 168; rgb[BurntSienna].g     =  89; rgb[BurntSienna].b     =  60;
	rgb[CarrotOrange].r    = 204; rgb[CarrotOrange].g    =  87; rgb[CarrotOrange].b    =  44;
	rgb[ChineseRed].r      = 255; rgb[ChineseRed].g      =  93; rgb[ChineseRed].b      =  32;
	rgb[Peach].r           = 235; rgb[Peach].g           = 192; rgb[Peach].b           = 175;
	rgb[CocoaBrown].r      = 117; rgb[CocoaBrown].g      =  76; rgb[CocoaBrown].b      =  56;
	rgb[Ivory].r           = 227; rgb[Ivory].g           = 212; rgb[Ivory].b           = 202;
	rgb[RawSienna].r       = 187; rgb[RawSienna].g       = 100; rgb[RawSienna].b       =  33;
	rgb[Brown].r           = 115; rgb[Brown].g           =  78; rgb[Brown].b           =  49;
	rgb[Apricot].r         = 221; rgb[Apricot].g         = 162; rgb[Apricot].b         = 115;
	rgb[EcruBeige].r       = 248; rgb[EcruBeige].g       = 207; rgb[EcruBeige].b       = 174;
	rgb[Tan].r             = 165; rgb[Tan].g             = 111; rgb[Tan].b             =  63;
	rgb[Cork].r            = 165; rgb[Cork].g            = 129; rgb[Cork].b            =  97;
	rgb[Beige].r           = 193; rgb[Beige].g           = 171; rgb[Beige].b           = 150;
	rgb[Orange].r          = 253; rgb[Orange].g          = 126; rgb[Orange].b          =   0;
	rgb[Buff].r            = 197; rgb[Buff].g            = 153; rgb[Buff].b            = 109;
	rgb[GoldenYellow].r    = 243; rgb[GoldenYellow].g    = 154; rgb[GoldenYellow].b    =  56;
	rgb[Amber].r           = 179; rgb[Amber].g           = 125; rgb[Amber].b           =  64;
	rgb[Sepia].r           =  74; rgb[Sepia].g           =  59; rgb[Sepia].b           =  42;
	rgb[MandarinOrange].r  = 253; rgb[MandarinOrange].g  = 149; rgb[MandarinOrange].b  =  30;
	rgb[Bronze].r          = 129; rgb[Bronze].g          =  90; rgb[Bronze].b          =  43;
	rgb[BurntUmber].r      =  91; rgb[BurntUmber].g      =  70; rgb[BurntUmber].b      =  42;
	rgb[YellowOcher].r     = 193; rgb[YellowOcher].g     = 138; rgb[YellowOcher].b     =  57;
	rgb[Leghorn].r         = 225; rgb[Leghorn].g         = 197; rgb[Leghorn].b         = 155;
	rgb[Khaki].r           = 154; rgb[Khaki].g           = 117; rgb[Khaki].b           =  58;
	rgb[Blond].r           = 227; rgb[Blond].g           = 180; rgb[Blond].b           = 102;
	rgb[Marigold].r        = 255; rgb[Marigold].g        = 160; rgb[Marigold].b        =   0;
	rgb[NaplesYellow].r    = 242; rgb[NaplesYellow].g    = 194; rgb[NaplesYellow].b    = 107;
	rgb[CreamYellow].r     = 232; rgb[CreamYellow].g     = 213; rgb[CreamYellow].b     = 175;
	rgb[RawUmber].r        = 127; rgb[RawUmber].g        =  92; rgb[RawUmber].b        =  19;
	rgb[ChromeYellow].r    = 255; rgb[ChromeYellow].g    = 188; rgb[ChromeYellow].b    =   0;
	rgb[OliveDrab].r       = 104; rgb[OliveDrab].g       =  98; rgb[OliveDrab].b       =  78;
	rgb[CanaryYellow].r    = 247; rgb[CanaryYellow].g    = 213; rgb[CanaryYellow].b    =  78;
	rgb[Yellow].r          = 255; rgb[Yellow].g          = 204; rgb[Yellow].b          =   0;
	rgb[Olive].r           =  96; rgb[Olive].g           =  86; rgb[Olive].b           =  39;
	rgb[LemonYellow].r     = 232; rgb[LemonYellow].g     = 200; rgb[LemonYellow].b     =   0;
	rgb[OliveGreen].r      =  86; rgb[OliveGreen].g      =  88; rgb[OliveGreen].b      =  56;
	rgb[GrassGreen].r      = 115; rgb[GrassGreen].g      = 124; rgb[GrassGreen].b      =  62;
	rgb[ChartreuseGreen].r = 189; rgb[ChartreuseGreen].g = 212; rgb[ChartreuseGreen].b =  88;
	rgb[LeafGreen].r       = 135; rgb[LeafGreen].g       = 157; rgb[LeafGreen].b       =  78;
	rgb[SeaGreen].r        = 154; rgb[SeaGreen].g        = 185; rgb[SeaGreen].b        =  97;
	rgb[IvyGreen].r        =  81; rgb[IvyGreen].g        = 106; rgb[IvyGreen].b        =  57;
	rgb[AppleGreen].r      = 176; rgb[AppleGreen].g      = 211; rgb[AppleGreen].b      = 168;
	rgb[MintGreen].r       = 129; rgb[MintGreen].g       = 204; rgb[MintGreen].b       = 145;
	rgb[Green].r           =  42; rgb[Green].g           = 155; rgb[Green].b           =  80;
	rgb[CobaltGreen].r     =  93; rgb[CobaltGreen].g     = 194; rgb[CobaltGreen].b     = 136;
	rgb[EmeraldGreen].r    =  77; rgb[EmeraldGreen].g    = 165; rgb[EmeraldGreen].b    = 115;
	rgb[BottleGreen].r     =  38; rgb[BottleGreen].g     =  68; rgb[BottleGreen].b     =  53;
	rgb[ForestGreen].r     =  62; rgb[ForestGreen].g     = 121; rgb[ForestGreen].b     =  92;
	rgb[MalachiteGreen].r  =   0; rgb[MalachiteGreen].g  = 128; rgb[MalachiteGreen].b  =  71;
	rgb[Viridian].r        =  21; rgb[Viridian].g        = 111; rgb[Viridian].b        =  92;
	rgb[BilliardGreen].r   =   0; rgb[BilliardGreen].g   =  72; rgb[BilliardGreen].b   =  64;
	rgb[PeacockGreen].r    =   0; rgb[PeacockGreen].g    = 127; rgb[PeacockGreen].b    = 145;
	rgb[PeacockBlue].r     =   0; rgb[PeacockBlue].g     = 112; rgb[PeacockBlue].b     = 139;
	rgb[NileBlue].r        =  81; rgb[NileBlue].g        = 144; rgb[NileBlue].b        = 164;
	rgb[MarineBlue].r      =   0; rgb[MarineBlue].g      =  81; rgb[MarineBlue].b      = 117;
	rgb[TurquoiseBlue].r   =  57; rgb[TurquoiseBlue].g   = 158; rgb[TurquoiseBlue].b   = 204;
	rgb[Cyan].r            =  33; rgb[Cyan].g            = 157; rgb[Cyan].b            = 221;
	rgb[CeruleanBlue].r    =  11; rgb[CeruleanBlue].g    = 116; rgb[CeruleanBlue].b    = 175;
	rgb[HorizonBlue].r     = 145; rgb[HorizonBlue].g     = 178; rgb[HorizonBlue].b     = 210;
	rgb[SkyBlue].r         = 149; rgb[SkyBlue].g         = 192; rgb[SkyBlue].b         = 236;
	rgb[MidnightBlue].r    =   0; rgb[MidnightBlue].g    =  21; rgb[MidnightBlue].b    =  45;
	rgb[Blue].r            =  49; rgb[Blue].g            = 112; rgb[Blue].b            = 185;
	rgb[CobaltBlue].r      =  40; rgb[CobaltBlue].g      =  99; rgb[CobaltBlue].b      = 171;
	rgb[SaxBlue].r         =  98; rgb[SaxBlue].g         = 125; rgb[SaxBlue].b         = 161;
	rgb[BabyBlue].r        = 171; rgb[BabyBlue].g        = 189; rgb[BabyBlue].b        = 218;
	rgb[IronBlue].r        =  61; rgb[IronBlue].g        =  73; rgb[IronBlue].b        = 107;
	rgb[Hyacinth].r        = 117; rgb[Hyacinth].g        = 134; rgb[Hyacinth].b        = 187;
	rgb[NavyBlue].r        =  51; rgb[NavyBlue].g        =  60; rgb[NavyBlue].b        =  94;
	rgb[UltramarineBlue].r =  65; rgb[UltramarineBlue].g =  79; rgb[UltramarineBlue].b = 163;
	rgb[OrientalBlue].r    =  55; rgb[OrientalBlue].g    =  67; rgb[OrientalBlue].b    = 143;
	rgb[SkyGray].r         = 186; rgb[SkyGray].g         = 186; rgb[SkyGray].b         = 198;
	rgb[Wistaria].r        = 119; rgb[Wistaria].g        = 110; rgb[Wistaria].b        = 210;
	rgb[SlateGray].r       =  86; rgb[SlateGray].g       =  85; rgb[SlateGray].b       =  94;
	rgb[Pansy].r           =  64; rgb[Pansy].g           =  49; rgb[Pansy].b           = 126;
	rgb[Heliotrope].r      = 131; rgb[Heliotrope].g      = 109; rgb[Heliotrope].b      = 197;
	rgb[Violet].r          = 109; rgb[Violet].g          =  82; rgb[Violet].b          = 171;
	rgb[Mauve].r           = 131; rgb[Mauve].g           =  95; rgb[Mauve].b           = 168;
	rgb[Lavender].r        = 158; rgb[Lavender].g        = 142; rgb[Lavender].b        = 174;
	rgb[CharcoalGray].r    =  78; rgb[CharcoalGray].g    =  72; rgb[CharcoalGray].b    =  84;
	rgb[SteelGray].r       = 115; rgb[SteelGray].g       = 108; rgb[SteelGray].b       = 121;
	rgb[Lilac].r           = 194; rgb[Lilac].g           = 162; rgb[Lilac].b           = 218;
	rgb[Purple].r          = 162; rgb[Purple].g          =  96; rgb[Purple].b          = 191;
	rgb[Orchid].r          = 199; rgb[Orchid].g          = 161; rgb[Orchid].b          = 215;
	rgb[Magenta].r         = 201; rgb[Magenta].g         =  73; rgb[Magenta].b         = 162;
	rgb[CherryPink].r      = 207; rgb[CherryPink].g      =  97; rgb[CherryPink].b      = 165;
	rgb[RoseRed].r         = 199; rgb[RoseRed].g         =  79; rgb[RoseRed].b         = 144;
	rgb[RubyRed].r         = 185; rgb[RubyRed].g         =  30; rgb[RubyRed].b         = 104;
	rgb[RoseGray].r        = 147; rgb[RoseGray].g        = 132; rgb[RoseGray].b        = 139;
	rgb[CochinealRed].r    = 175; rgb[CochinealRed].g    =  49; rgb[CochinealRed].b    = 104;
	rgb[WineRed].r         = 131; rgb[WineRed].g         =  39; rgb[WineRed].b         =  78;
	rgb[Strawberry].r      = 187; rgb[Strawberry].g      =  30; rgb[Strawberry].b      =  94;
	rgb[Burgundy].r        =  69; rgb[Burgundy].g        =  42; rgb[Burgundy].b        =  53;
	rgb[RosePink].r        = 239; rgb[RosePink].g        = 147; rgb[RosePink].b        = 182;
	rgb[Rose].r            = 217; rgb[Rose].g            =  65; rgb[Rose].b            = 119;
	rgb[OldRose].r         = 201; rgb[OldRose].g         = 127; rgb[OldRose].b         = 150;
	rgb[CoralRed].r        = 255; rgb[CoralRed].g        = 135; rgb[CoralRed].b        = 160;
	rgb[Pink].r            = 235; rgb[Pink].g            = 151; rgb[Pink].b            = 168;
	rgb[Carmine].r         = 190; rgb[Carmine].g         =  30; rgb[Carmine].b         =  62;
	rgb[Bordeaux].r        =  85; rgb[Bordeaux].g        =  53; rgb[Bordeaux].b        =  59;
	rgb[BabyPink].r        = 255; rgb[BabyPink].g        = 201; rgb[BabyPink].b        = 210;
	rgb[SignalRed].r       = 206; rgb[SignalRed].g       =  49; rgb[SignalRed].b       =  74;
	rgb[PoppyRed].r        = 221; rgb[PoppyRed].g        =  65; rgb[PoppyRed].b        =  87;
	rgb[Red].r             = 222; rgb[Red].g             =  66; rgb[Red].b             =  76;
	rgb[Maroon].r          = 104; rgb[Maroon].g          =  42; rgb[Maroon].b          =  43;
}
int Color::MakeColorHandle(int ColorHandleNum) {
	if (ColorHandleNum < 0 || ColorHandleNum > ColorNum) return -1;
	for (int i = 0; i < ColorHandleNum; i++) { rgb[i].c = GetColor(rgb[i].r, rgb[i].g, rgb[i].b); rgb[i].available = true; } return 0;
}
unsigned int Color::CreateColorToHandle(int ColorNo) {
	if (ColorNo < 0 || ColorNo >= ColorNum) return 0;
	rgb[ColorNo].c = GetColor(rgb[ColorNo].r, rgb[ColorNo].g, rgb[ColorNo].b); rgb[ColorNo].available = true; return rgb[ColorNo].c;
};
unsigned int Color::GetColorHandle(int ColorNo) {
	if (ColorNo < 0 || ColorNo >= ColorNum) return 0; if (!rgb[ColorNo].available) return 0; return rgb[ColorNo].c;
}
Color::~Color() {
}