//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Resource.rc で使用
//
#define IDB_PNG1                         1
#define IDB_PNG2                         2
#define IDB_PNG3                         3
#define IDB_PNG4                         4
#define IDB_PNG5                         5
#define IDB_PNG6                         6
#define IDB_PNG7                         7
#define IDB_PNG8                         8
#define IDB_PNG9                         9
#define IDB_PNG10                        10
#define IDB_PNG11                        11
#define IDB_PNG12                        14
#define IDB_PNG13                        15
#define IDB_PNG14                        16
#define IDB_PNG15                        17
#define IDB_PNG16                        18
#define IDB_PNG17                        19
#define IDB_PNG18                        20
#define IDB_PNG19                        21
#define IDB_PNG20                        22
#define IDB_PNG21                        23
#define IDB_PNG22                        24
#define IDB_PNG23                        25
#define IDB_PNG24                        28
#define IDB_PNG25                        29
#define IDB_PNG26                        30
#define IDB_PNG27                        31
#define IDB_PNG28                        32
#define IDB_PNG29                        33
#define IDB_PNG30                        34
#define IDB_PNG31                        35
#define IDB_PNG32                        36
#define IDB_PNG33                        37
#define IDB_PNG34                        38
#define IDB_PNG35                        42
#define IDB_PNG36                        44
#define IDB_PNG37                        45
#define IDB_PNG38                        46
#define IDB_PNG39                        47
#define IDB_PNG40                        48
#define IDB_PNG41                        49
#define IDB_PNG42                        50
#define IDB_PNG43                        54
#define IDB_PNG44                        56
#define IDB_PNG45                        57
#define IDB_PNG46                        58
#define IDB_PNG47                        59
#define IDB_PNG48                        60
#define IDB_PNG49                        61
#define IDB_PNG50                        62
#define IDB_PNG51                        63
#define IDB_PNG52                        64
#define IDB_PNG53                        65
#define IDB_PNG54                        66
#define IDB_PNG55                        67
#define IDB_PNG56                        68
#define IDB_PNG57                        87
#define IDB_PNG58                        88
#define IDB_PNG59                        157
#define IDB_PNG60                        184
#define IDB_PNG61                        197
#define IDB_PNG62                        200
#define IDB_PNG63                        203
#define IDB_PNG64                        205
#define IDB_PNG65                        208
#define IDB_PNG66                        210
#define IDB_PNG67                        211
#define IDB_PNG68                        300
#define IDB_PNG69                        301
#define IDB_PNG70                        302
#define IDB_PNG71                        303
#define IDB_PNG72                        304
#define IDB_PNG73                        305
#define IDB_PNG74                        306
#define IDB_PNG75                        307
#define IDB_PNG76                        308
#define IDB_PNG77                        309
#define IDB_PNG78                        310
#define IDB_PNG79                        311
#define IDB_PNG80                        312
#define IDB_PNG81                        313
#define IDB_PNG82                        314
#define IDB_PNG83                        315
#define IDB_PNG84                        316
#define IDB_PNG85                        317
#define IDB_PNG86                        318
#define IDB_PNG87                        319
#define IDB_PNG88                        320
#define IDB_PNG89                        321
#define IDB_PNG90                        322
#define IDB_PNG91                        323
#define IDB_PNG92                        324
#define IDB_PNG93                        325
#define IDB_PNG94                        326
#define IDB_PNG95                        327
#define IDB_PNG96                        328
#define IDB_PNG97                        329
#define IDB_PNG98                        330
#define IDB_PNG99                        331
#define IDB_PNG100                       332
#define IDB_PNG101                       333
#define IDI_ICON1                        350
#define IDR_WAVE1                        400
#define IDR_WAVE2                        401
#define IDR_WAVE3                        402
#define IDR_WAVE4                        403
#define IDR_WAVE5                        404
#define IDR_WAVE6                        405
#define IDR_WAVE7                        406
#define IDR_WAVE8                        407
#define IDR_WAVE9                        408
#define IDR_WAVE10                       409
#define IDR_WAVE11                       410
#define IDR_WAVE12                       411
#define IDR_WAVE13                       412
#define IDR_WAVE14                       413
#define IDR_WAVE15                       414
#define IDR_WAVE16                       415
#define IDR_WAVE17                       416
#define IDR_WAVE18                       417
#define IDR_WAVE19                       418
#define IDR_WAVE20                       419

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
